import type { EngineExercise } from "@/lib/training-engine/types";

type ExerciseSeed = Omit<EngineExercise, "id">;

function exercise(seed: ExerciseSeed): EngineExercise {
  return {
    id: 0,
    secondaryMuscles: [],
    environments: [],
    tags: [],
    alternatives: [],
    contraindications: [],
    ...seed,
  };
}

const SEEDS: ExerciseSeed[] = [
  exercise({
    slug: "chest-press-macchina",
    name: "Chest Press Macchina",
    category: "strength",
    primaryMuscle: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "horizontal_push",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy", "beginner_friendly"],
    alternatives: ["panca-piana-manubri", "bench-press"],
  }),
  exercise({
    slug: "chest-press-inclinata",
    name: "Chest Press Inclinata",
    category: "strength",
    primaryMuscle: "petto alto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "horizontal_push",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy", "beginner_friendly"],
    alternatives: ["incline-dumbbell-press", "chest-press-macchina"],
  }),
  exercise({
    slug: "bench-press",
    name: "Bench Press",
    category: "strength",
    primaryMuscle: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "bilanciere",
    difficulty: "advanced",
    movementPattern: "horizontal_push",
    environments: ["gym"],
    tags: ["compound", "barbell", "strength"],
    alternatives: ["panca-piana-manubri"],
  }),
  exercise({
    slug: "panca-piana-manubri",
    name: "Panca Piana Manubri",
    category: "strength",
    primaryMuscle: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "horizontal_push",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "hypertrophy", "beginner_friendly"],
    alternatives: ["incline-dumbbell-press", "push-up-inclinati"],
  }),
  exercise({
    slug: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "strength",
    primaryMuscle: "petto alto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "manubri",
    difficulty: "intermediate",
    movementPattern: "horizontal_push",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "hypertrophy"],
    alternatives: ["chest-press-inclinata", "panca-piana-manubri"],
  }),
  exercise({
    slug: "push-up-inclinati",
    name: "Push-up Inclinati",
    category: "strength",
    primaryMuscle: "petto",
    secondaryMuscles: ["tricipiti", "spalle"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "horizontal_push",
    environments: ["home", "gym", "outdoor"],
    tags: ["compound", "bodyweight", "beginner_friendly", "low_impact"],
    alternatives: ["panca-piana-manubri"],
  }),
  exercise({
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "horizontal_pull",
    environments: ["gym"],
    tags: ["compound", "cable", "hypertrophy", "beginner_friendly"],
    alternatives: ["rematore-macchina", "rematore-con-manubrio"],
  }),
  exercise({
    slug: "rematore-macchina",
    name: "Rematore Macchina",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "horizontal_pull",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy", "beginner_friendly"],
    alternatives: ["seated-cable-row", "rematore-con-manubrio"],
  }),
  exercise({
    slug: "rematore-con-manubrio",
    name: "Rematore con Manubrio",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "horizontal_pull",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "hypertrophy", "beginner_friendly"],
    alternatives: ["seated-cable-row", "bodyweight-row-tavolo"],
  }),
  exercise({
    slug: "bodyweight-row-tavolo",
    name: "Bodyweight Row al Tavolo",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti", "deltoidi posteriori"],
    equipment: "corpo libero",
    difficulty: "intermediate",
    movementPattern: "horizontal_pull",
    environments: ["home"],
    tags: ["compound", "bodyweight", "low_impact"],
    alternatives: ["rematore-con-manubrio"],
  }),
  exercise({
    slug: "lat-machine-avanti",
    name: "Lat Machine Avanti",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "vertical_pull",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy", "beginner_friendly"],
    alternatives: ["neutral-grip-lat-pulldown", "assisted-pull-up"],
  }),
  exercise({
    slug: "neutral-grip-lat-pulldown",
    name: "Neutral Grip Lat Pulldown",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "vertical_pull",
    environments: ["gym"],
    tags: ["compound", "cable", "hypertrophy", "beginner_friendly"],
    alternatives: ["lat-machine-avanti"],
  }),
  exercise({
    slug: "assisted-pull-up",
    name: "Assisted Pull-up",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti"],
    equipment: "macchina",
    difficulty: "intermediate",
    movementPattern: "vertical_pull",
    environments: ["gym"],
    tags: ["compound", "machine", "strength"],
    alternatives: ["lat-machine-avanti"],
  }),
  exercise({
    slug: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["bicipiti"],
    equipment: "elastici",
    difficulty: "beginner",
    movementPattern: "vertical_pull",
    environments: ["home"],
    tags: ["compound", "band", "beginner_friendly", "low_impact"],
    alternatives: ["lat-machine-avanti"],
  }),
  exercise({
    slug: "alzate-laterali",
    name: "Alzate Laterali",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["deltoidi laterali"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "shoulder_abduction",
    environments: ["gym", "home"],
    tags: ["isolation", "dumbbell", "hypertrophy", "shoulder_friendly"],
    alternatives: ["alzate-laterali-ai-cavi", "lateral-raise-machine"],
  }),
  exercise({
    slug: "alzate-laterali-ai-cavi",
    name: "Alzate Laterali ai Cavi",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["deltoidi laterali"],
    equipment: "cavi",
    difficulty: "intermediate",
    movementPattern: "shoulder_abduction",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy", "shoulder_friendly"],
    alternatives: ["alzate-laterali", "lateral-raise-machine"],
  }),
  exercise({
    slug: "lateral-raise-machine",
    name: "Lateral Raise Machine",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["deltoidi laterali"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "shoulder_abduction",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy", "shoulder_friendly"],
    alternatives: ["alzate-laterali"],
  }),
  exercise({
    slug: "face-pull",
    name: "Face Pull",
    category: "strength",
    primaryMuscle: "deltoidi posteriori",
    secondaryMuscles: ["dorsali", "spalle"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "horizontal_pull",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy", "shoulder_friendly"],
    alternatives: ["reverse-fly-machine", "reverse-fly-ai-cavi"],
  }),
  exercise({
    slug: "reverse-fly-machine",
    name: "Reverse Fly Machine",
    category: "strength",
    primaryMuscle: "deltoidi posteriori",
    secondaryMuscles: ["dorsali", "spalle"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "horizontal_pull",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy", "shoulder_friendly"],
    alternatives: ["face-pull", "reverse-fly-ai-cavi"],
  }),
  exercise({
    slug: "reverse-fly-ai-cavi",
    name: "Reverse Fly ai Cavi",
    category: "strength",
    primaryMuscle: "deltoidi posteriori",
    secondaryMuscles: ["spalle"],
    equipment: "cavi",
    difficulty: "intermediate",
    movementPattern: "horizontal_pull",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy", "shoulder_friendly"],
    alternatives: ["reverse-fly-machine"],
  }),
  exercise({
    slug: "seated-dumbbell-press",
    name: "Seated Dumbbell Press",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: "manubri",
    difficulty: "intermediate",
    movementPattern: "vertical_push",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "hypertrophy"],
    contraindications: ["shoulder"],
  }),
  exercise({
    slug: "shoulder-press-machine",
    name: "Shoulder Press Machine",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["tricipiti"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "vertical_push",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy"],
    contraindications: ["shoulder"],
  }),
  exercise({
    slug: "landmine-press",
    name: "Landmine Press",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["petto", "tricipiti"],
    equipment: "bilanciere",
    difficulty: "intermediate",
    movementPattern: "vertical_push",
    environments: ["gym"],
    tags: ["compound", "barbell", "shoulder_friendly", "strength"],
  }),
  exercise({
    slug: "curl-manubri",
    name: "Curl Manubri",
    category: "strength",
    primaryMuscle: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "elbow_flexion",
    environments: ["gym", "home"],
    tags: ["isolation", "dumbbell", "hypertrophy"],
    alternatives: ["curl-cavo", "hammer-curl"],
  }),
  exercise({
    slug: "curl-cavo",
    name: "Curl Cavo",
    category: "strength",
    primaryMuscle: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "elbow_flexion",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy"],
    alternatives: ["curl-manubri", "preacher-curl-macchina"],
  }),
  exercise({
    slug: "preacher-curl-macchina",
    name: "Preacher Curl Macchina",
    category: "strength",
    primaryMuscle: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "elbow_flexion",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy"],
    alternatives: ["curl-cavo"],
  }),
  exercise({
    slug: "hammer-curl",
    name: "Hammer Curl",
    category: "strength",
    primaryMuscle: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "elbow_flexion",
    environments: ["gym", "home"],
    tags: ["isolation", "dumbbell", "hypertrophy"],
    alternatives: ["curl-manubri"],
  }),
  exercise({
    slug: "triceps-pushdown",
    name: "Triceps Pushdown",
    category: "strength",
    primaryMuscle: "tricipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "elbow_extension",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy"],
    alternatives: ["pushdown-barra", "triceps-machine"],
  }),
  exercise({
    slug: "pushdown-barra",
    name: "Pushdown Barra",
    category: "strength",
    primaryMuscle: "tricipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "cavi",
    difficulty: "beginner",
    movementPattern: "elbow_extension",
    environments: ["gym"],
    tags: ["isolation", "cable", "hypertrophy"],
    alternatives: ["triceps-pushdown", "triceps-machine"],
  }),
  exercise({
    slug: "triceps-machine",
    name: "Triceps Machine",
    category: "strength",
    primaryMuscle: "tricipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "elbow_extension",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy"],
    alternatives: ["triceps-pushdown"],
  }),
  exercise({
    slug: "diamond-push-up",
    name: "Diamond Push-up",
    category: "strength",
    primaryMuscle: "tricipiti",
    secondaryMuscles: ["petto"],
    equipment: "corpo libero",
    difficulty: "intermediate",
    movementPattern: "elbow_extension",
    environments: ["home", "outdoor"],
    tags: ["isolation", "bodyweight", "low_impact"],
  }),
  exercise({
    slug: "towel-biceps-curl-isometric",
    name: "Towel Biceps Curl Isometric",
    category: "strength",
    primaryMuscle: "bicipiti",
    secondaryMuscles: ["avambracci"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "elbow_flexion",
    environments: ["home"],
    tags: ["isolation", "bodyweight", "low_impact", "beginner_friendly"],
  }),
  exercise({
    slug: "bodyweight-triceps-extension-wall",
    name: "Bodyweight Triceps Extension Wall",
    category: "strength",
    primaryMuscle: "tricipiti",
    secondaryMuscles: ["petto"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "elbow_extension",
    environments: ["home"],
    tags: ["isolation", "bodyweight", "low_impact", "beginner_friendly"],
  }),
  exercise({
    slug: "leg-press",
    name: "Leg Press",
    category: "strength",
    primaryMuscle: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "squat",
    environments: ["gym"],
    tags: ["compound", "machine", "strength", "hypertrophy", "beginner_friendly"],
  } as ExerciseSeed),
  exercise({
    slug: "hack-squat",
    name: "Hack Squat",
    category: "strength",
    primaryMuscle: "quadricipiti",
    secondaryMuscles: ["glutei"],
    equipment: "macchina",
    difficulty: "intermediate",
    movementPattern: "squat",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy"],
    contraindications: ["knee"],
  }),
  exercise({
    slug: "goblet-squat",
    name: "Goblet Squat",
    category: "strength",
    primaryMuscle: "quadricipiti",
    secondaryMuscles: ["glutei", "core"],
    equipment: "manubri",
    difficulty: "beginner",
    movementPattern: "squat",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "beginner_friendly"],
  }),
  exercise({
    slug: "box-squat-chair",
    name: "Box Squat alla Sedia",
    category: "strength",
    primaryMuscle: "quadricipiti",
    secondaryMuscles: ["glutei", "core"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "squat",
    environments: ["home"],
    tags: ["compound", "bodyweight", "beginner_friendly", "low_impact"],
  }),
  exercise({
    slug: "wall-slide",
    name: "Wall Slide",
    category: "strength",
    primaryMuscle: "spalle",
    secondaryMuscles: ["deltoidi posteriori"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "shoulder_abduction",
    environments: ["home"],
    tags: [
      "isolation",
      "bodyweight",
      "low_impact",
      "shoulder_friendly",
      "beginner_friendly",
    ],
  }),
  exercise({
    slug: "hip-thrust",
    name: "Hip Thrust",
    category: "strength",
    primaryMuscle: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: "bilanciere",
    difficulty: "intermediate",
    movementPattern: "hip_extension",
    environments: ["gym"],
    tags: ["compound", "barbell", "hypertrophy", "strength"],
    alternatives: ["glute-bridge"],
  }),
  exercise({
    slug: "glute-bridge",
    name: "Glute Bridge",
    category: "strength",
    primaryMuscle: "glutei",
    secondaryMuscles: ["femorali", "core"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "hip_extension",
    environments: ["home", "gym"],
    tags: ["compound", "bodyweight", "beginner_friendly", "low_impact"],
    alternatives: ["hip-thrust", "single-leg-hip-bridge"],
  }),
  exercise({
    slug: "single-leg-hip-bridge",
    name: "Single Leg Hip Bridge",
    category: "strength",
    primaryMuscle: "glutei",
    secondaryMuscles: ["femorali", "core"],
    equipment: "corpo libero",
    difficulty: "intermediate",
    movementPattern: "hip_extension",
    environments: ["home"],
    tags: ["compound", "bodyweight", "low_impact", "unilateral"],
  }),
  exercise({
    slug: "back-extension-glute-focus",
    name: "Back Extension Glute Focus",
    category: "strength",
    primaryMuscle: "glutei",
    secondaryMuscles: ["femorali"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "hip_extension",
    environments: ["gym"],
    tags: ["compound", "machine", "hypertrophy"],
  }),
  exercise({
    slug: "leg-curl-macchina",
    name: "Leg Curl Macchina",
    category: "strength",
    primaryMuscle: "femorali",
    secondaryMuscles: ["glutei"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "knee_flexion",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy", "beginner_friendly"],
    alternatives: ["leg-curl-fitball", "romanian-deadlift-con-manubri"],
  }),
  exercise({
    slug: "leg-curl-fitball",
    name: "Leg Curl Fitball",
    category: "strength",
    primaryMuscle: "femorali",
    secondaryMuscles: ["glutei", "core"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "knee_flexion",
    environments: ["home"],
    tags: ["isolation", "bodyweight", "beginner_friendly", "low_impact"],
    alternatives: ["leg-curl-macchina"],
  }),
  exercise({
    slug: "romanian-deadlift-con-manubri",
    name: "Romanian Deadlift con Manubri",
    category: "strength",
    primaryMuscle: "femorali",
    secondaryMuscles: ["glutei", "erettori spinali"],
    equipment: "manubri",
    difficulty: "intermediate",
    movementPattern: "hinge",
    environments: ["gym", "home"],
    tags: ["compound", "dumbbell", "strength"],
    contraindications: ["back"],
  }),
  exercise({
    slug: "calf-raise",
    name: "Calf Raise",
    category: "strength",
    primaryMuscle: "polpacci",
    secondaryMuscles: ["caviglie"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "knee_extension",
    environments: ["home", "gym"],
    tags: ["isolation", "bodyweight", "beginner_friendly"],
    alternatives: ["seated-calf-raise"],
  }),
  exercise({
    slug: "seated-calf-raise",
    name: "Seated Calf Raise",
    category: "strength",
    primaryMuscle: "polpacci",
    secondaryMuscles: ["caviglie"],
    equipment: "macchina",
    difficulty: "beginner",
    movementPattern: "knee_extension",
    environments: ["gym"],
    tags: ["isolation", "machine", "hypertrophy"],
    alternatives: ["calf-raise"],
  }),
  exercise({
    slug: "dead-bug",
    name: "Dead Bug",
    category: "core",
    primaryMuscle: "core",
    secondaryMuscles: ["addome", "obliqui"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "core_anti_extension",
    environments: ["home", "gym"],
    tags: ["core_anti_extension", "stability", "low_impact", "beginner_friendly"],
    alternatives: ["pallof-press", "plank"],
  }),
  exercise({
    slug: "pallof-press",
    name: "Pallof Press",
    category: "core",
    primaryMuscle: "core",
    secondaryMuscles: ["obliqui"],
    equipment: "elastici",
    difficulty: "beginner",
    movementPattern: "core_anti_rotation",
    environments: ["home", "gym"],
    tags: ["core_anti_rotation", "stability", "low_impact", "beginner_friendly", "band"],
    alternatives: ["side-plank"],
  }),
  exercise({
    slug: "plank",
    name: "Plank",
    category: "core",
    primaryMuscle: "core",
    secondaryMuscles: ["addome", "spalle"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "core_anti_extension",
    environments: ["home", "gym"],
    tags: ["stability", "low_impact", "bodyweight", "beginner_friendly"],
    alternatives: ["dead-bug", "side-plank"],
  }),
  exercise({
    slug: "side-plank",
    name: "Side Plank",
    category: "core",
    primaryMuscle: "core",
    secondaryMuscles: ["obliqui"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "core_anti_rotation",
    environments: ["home", "gym"],
    tags: ["stability", "low_impact", "bodyweight", "beginner_friendly"],
    alternatives: ["pallof-press"],
  }),
  exercise({
    slug: "bird-dog",
    name: "Bird Dog",
    category: "core",
    primaryMuscle: "core",
    secondaryMuscles: ["glutei"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "core_anti_rotation",
    environments: ["home", "gym"],
    tags: ["stability", "low_impact", "bodyweight", "beginner_friendly"],
  }),
  exercise({
    slug: "mobility-anche",
    name: "Mobilita Anche",
    category: "mobility",
    primaryMuscle: "anche",
    secondaryMuscles: ["glutei"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "mobility",
    environments: ["home", "gym"],
    tags: ["mobility", "prehab", "low_impact", "warmup"],
  }),
  exercise({
    slug: "mobility-spalle",
    name: "Mobilita Spalle",
    category: "mobility",
    primaryMuscle: "spalle",
    secondaryMuscles: ["torace"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "mobility",
    environments: ["home", "gym"],
    tags: ["mobility", "prehab", "low_impact", "warmup", "shoulder_friendly"],
  }),
  exercise({
    slug: "mobility-caviglie",
    name: "Mobilita Caviglie",
    category: "mobility",
    primaryMuscle: "caviglie",
    secondaryMuscles: ["polpacci"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "mobility",
    environments: ["home", "gym"],
    tags: ["mobility", "prehab", "low_impact", "warmup"],
  }),
  exercise({
    slug: "thoracic-rotation",
    name: "Thoracic Rotation",
    category: "mobility",
    primaryMuscle: "colonna toracica",
    secondaryMuscles: ["spalle"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "mobility",
    environments: ["home", "gym"],
    tags: ["mobility", "prehab", "low_impact", "warmup"],
  }),
  exercise({
    slug: "prone-lat-sweep",
    name: "Prone Lat Sweep",
    category: "strength",
    primaryMuscle: "dorsali",
    secondaryMuscles: ["deltoidi posteriori"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "vertical_pull",
    environments: ["home"],
    tags: ["compound", "bodyweight", "low_impact", "beginner_friendly"],
  }),
  exercise({
    slug: "bike-cyclette",
    name: "Bike Cyclette",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadricipiti", "glutei"],
    equipment: "cyclette",
    difficulty: "beginner",
    movementPattern: "cardio",
    environments: ["gym", "home"],
    tags: ["cardio", "conditioning", "low_impact", "bike"],
  }),
  exercise({
    slug: "camminata-inclinata",
    name: "Camminata Inclinata",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["glutei", "quadricipiti"],
    equipment: "tapis roulant",
    difficulty: "beginner",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning", "low_impact", "treadmill"],
  }),
  exercise({
    slug: "camminata-treadmill",
    name: "Camminata Treadmill",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadricipiti"],
    equipment: "tapis roulant",
    difficulty: "beginner",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning", "low_impact", "treadmill"],
  }),
  exercise({
    slug: "ellittica",
    name: "Ellittica",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadricipiti", "glutei"],
    equipment: "ellittica",
    difficulty: "beginner",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning", "low_impact", "elliptical"],
  }),
  exercise({
    slug: "vogatore",
    name: "Vogatore",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["dorsali", "glutei"],
    equipment: "vogatore",
    difficulty: "intermediate",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning", "rower"],
  }),
  exercise({
    slug: "stair-climber",
    name: "Stair Climber",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["glutei", "quadricipiti"],
    equipment: "stair climber",
    difficulty: "intermediate",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning"],
    contraindications: ["knee"],
  }),
  exercise({
    slug: "assault-bike",
    name: "Assault Bike",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["quadricipiti"],
    equipment: "bike",
    difficulty: "intermediate",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning", "bike"],
  }),
  exercise({
    slug: "camminata-veloce-outdoor",
    name: "Camminata Veloce Outdoor",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["glutei", "quadricipiti"],
    equipment: "corpo libero",
    difficulty: "beginner",
    movementPattern: "cardio",
    environments: ["outdoor", "home"],
    tags: ["cardio", "conditioning", "bodyweight", "low_impact"],
  }),
  exercise({
    slug: "mountain-climber",
    name: "Mountain Climber",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["core", "quadricipiti"],
    equipment: "corpo libero",
    difficulty: "intermediate",
    movementPattern: "cardio",
    environments: ["home", "gym"],
    tags: ["cardio", "conditioning", "bodyweight", "high_impact"],
    contraindications: ["knee"],
  }),
  exercise({
    slug: "battle-rope",
    name: "Battle Rope",
    category: "cardio",
    primaryMuscle: "cardio",
    secondaryMuscles: ["spalle", "core"],
    equipment: "corda",
    difficulty: "intermediate",
    movementPattern: "cardio",
    environments: ["gym"],
    tags: ["cardio", "conditioning"],
  }),
  exercise({
    slug: "farmer-walk",
    name: "Farmer Walk",
    category: "cardio",
    primaryMuscle: "core",
    secondaryMuscles: ["glutei", "quadricipiti"],
    equipment: "manubri",
    difficulty: "intermediate",
    movementPattern: "carry",
    environments: ["gym", "home"],
    tags: ["conditioning", "dumbbell", "low_impact"],
  }),
];

export const MOCK_ENGINE_EXERCISES: EngineExercise[] = SEEDS.map((seed, index) => ({
  id: index + 1,
  ...seed,
}));
